# Generated by Django 5.2 on 2025-04-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='User',
            new_name='user',
        ),
    ]
