# Generated by Django 5.2 on 2025-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='score',
            field=models.IntegerField(),
        ),
    ]
