# Generated by Django 4.2 on 2025-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password2",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="password1",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
