# Generated by Django 4.2 on 2025-05-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_password2_alter_user_password1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password1",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
