# Generated by Django 4.2 on 2025-05-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_password1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password1",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password2",
        ),
    ]
