# Generated by Django 5.2.1 on 2025-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
