# Generated by Django 4.2 on 2025-05-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_category_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
