# Generated by Django 4.2 on 2025-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_coupon_order_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="min_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="minimum order amount per coupon",
                max_digits=12,
            ),
        ),
    ]
