name: Django project test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose up -d

      - name: Wait for containers to be ready
        run: sleep 10  # یا healthcheck بهتره، ولی ساده‌ترین حالت اینه

      - name: Run Django tests
        run: docker exec web pytest
